# Generated by Django 2.2 on 2020-07-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
